[tool.poetry]
name = "umipy"
version = "1.0.6"
description = ""
authors = ["kesha1225"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
aiohttp = "^3.8.3"
pydantic = "^2.4.2"
PyNaCl = "^1.5.0"
mnemonic = "^0.20"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
